### ISSUE TITLE
make → npm scripts

### ISSUE THREAD

**Issue by yhor1e** [yhor1e/notes-and-todos#14]
マルチプラットフォームなど
検証する。

タスク連結
> アカベコ (@akabekobeko)さんが9:17 午後 on 月, 5月 23, 2016にツイートしました。
> watchify と stylus の CLI で watch も実現できるし、タスク連結や変数の定義も npm だけで可能になったし、gulp から npm-scripts に移行したときの不満点がほぼ解消された。
> (https://twitter.com/akabekobeko/status/734719911851790340?s=03)

**Comment by horiey** [comment]
[WIP] npm-scripts を使い倒そう! - Qiita

http://qiita.com/mysticatea/items/e9bf581fb28c5f1cd660

**Comment by horiey** [comment]
npm-scripts でクロスプラットフォームに環境変数を参照するための npm を作成してみた – アカベコマイリ

http://akabeko.me/blog/2016/05/cross-conf-env-1-0-release/

**Comment by yhor1e** [comment]
http://akabeko.me/blog/2015/08/npm-run-all-and-concurrently/

**Comment by yhor1e** [comment]
使用する ノードモジュールが オプションを適切に提供している場合に限り、npm scripts で完結するようにタスクが定義できる印象。特にwatchがどのような機能を提供しているかに影響を受ける。

例えば、ミニファイをしたい場合に、1つのファイルに結合する前提なのか、そうではないのかなど。

こまかいタスクをせってしたい場合はやはり gulp が便利。

make は Windows 環境で使用させるためにソフトウェアをインストールすることが必要という点がネックになる。
