### ISSUE TITLE
Flux

### ISSUE THREAD

**Issue by yhor1e** [yhor1e/notes-and-todos#16]
- Flux ？ 
- EventEmmiter ？

**Comment by yhor1e** [comment]
10分で実装するFlux
http://azu.github.io/slide/react-meetup/flux.html

**Comment by horiey** [comment]
node.jsのEventEmitterについてのメモ書き - 株式会社BEFOOL

http://befool.co.jp/blog/chainzhang/using-node-event-emmiter/

**Comment by horiey** [comment]
Node書くならEventEmitterについて知っとくべし
http://qiita.com/yuku_t/items/d69d3a2c7dafa7d04e87

EventEmitterの代わりにEventEmitter2を使う
http://yosuke-furukawa.hatenablog.com/entry/2013/12/28/145647

**Comment by yhor1e** [comment]
>そろそろ Redux でも試そうかなと思ったが、middleware がたくさんあってそれらを取捨選択するフェーズに入ってるようで辛そう。いまは material-flux で事足りてるけど乗り換えるとしたら Flux Util かな。
